import classnames from "classnames";
import Head from "next/head";
import { useDarkMode } from "../svc/service";

export default function Home() {
  const { colorMode, toggleDarkMode, isMounted } = useDarkMode();
  console.log("indeX", colorMode);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div
        id="mojstrip"
        className={classnames(colorMode, isMounted && "loaded")}
      >
        <h1>Hello World</h1>
        <button onClick={toggleDarkMode}>Dark mode</button>
      </div>
    </>
  );
}
